### ISSUE TITLE
Delete backup folder

### ISSUE THREAD

**Issue by Gounlaf** [codeideo/paranoik-backups#5]
Hi,

Is there a way to delete the "backup folder" when after using the TarCompressor ?

Thanks

**Comment by jordanjambazov** [comment]
You could use the Python `shutil` module for the purpose.

    import shutil
    shutil.rmtree(BACKUP_DIR)

**Comment by Gounlaf** [comment]
HI @jordanjambazov,

Thanks for the answer, I will try it

**Comment by Gounlaf** [comment]
Hi @jordanjambazov ; it's working perfectly !
Thanks
